shortenScheme: 'http'
shortenDomain: 'localhost'
shortenPort: '8080'
httpTlsCertPath: ''
httpTlsKeyPath: ''
httpHostname: 'localhost:8080'
httpBindProtocol: 'tcp'
httpReadTimeout: '5s'
httpWriteTimeout: '5s'
httpIdleTimeout: '5s'
cacheShards: 2048
cacheLifeWindow: '30s'
cacheCleanWindow: '60s'
cacheEntriesInWindow: 0
cacheMaxEntrySize: 32
cacheHardMaxSize: 512
neo4jSecure: ''
neo4jTarget: ''
neo4jUser: ''
neo4jPassword: ''
neo4jRealm: ''
