ShortenScheme: "http"
ShortenPort: ""
ShortenDomain: "localhost"
ServerTLSCertPath: ""
ServerTLSKeyPath: ""
HttpHostname: "localhost"
HttpProtocol: "tcp"
HTTPReadTimeout: "1s"
HTTPWriteTimeout: "1s"
HTTPIdleTimeout: "1s"
CacheShards: 2048
CacheLifeWindow: "30s"
CacheCleanWindow: "60s"
CacheMaxEntriesInWindow: 0
CacheMaxEntrySize: 32
CacheHardMaxCacheSize: 128
Neo4JSecure: False
Neo4JTarget: "bolt://localhost:7687"
Neo4JUser: "neo4j"
Neo4JPassword: "my-neo4j-password"
Neo4JRealm: "neo4j"